export const getCountryCode = (location: string): string => {
    if (!location) return '';

    const parts = location.split(',');
    const country = parts[parts.length - 1].trim();

    const countryCodes: Record<string, string> = {
        'France': 'FR',
        'USA': 'US',
        'Espagne': 'ES',
        'Spain': 'ES',
        'Belgique': 'BE',
        'Belgium': 'BE',
        'Royaume-Uni': 'GB',
        'UK': 'GB',
        'Allemagne': 'DE',
        'Germany': 'DE',
        'Italie': 'IT',
        'Italy': 'IT',
        'Pays-Bas': 'NL',
        'Netherlands': 'NL',
        'Croatie': 'HR',
        'Croatia': 'HR',
        'Brésil': 'BR',
        'Brazil': 'BR',
        'Japon': 'JP',
        'Japan': 'JP',
        'Suisse': 'CH',
        'Switzerland': 'CH',
        'Émirats Arabes Unis': 'AE',
        'UAE': 'AE',
        'Dubai': 'AE',
        'Mexique': 'MX',
        'Mexico': 'MX',
        'Portugal': 'PT',
        'Autriche': 'AT',
        'Austria': 'AT',
        'Etats Unis': 'US',
        'Etats-Unis': 'US',
        'États-Unis': 'US',
        'Suède': 'SE',
        'Sweden': 'SE',
        'Norvège': 'NO',
        'Norway': 'NO',
        'Danemark': 'DK',
        'Denmark': 'DK',
        'Finlande': 'FI',
        'Finland': 'FI',
        'Irlande': 'IE',
        'Ireland': 'IE',
        'Pologne': 'PL',
        'Poland': 'PL',
        'Grèce': 'GR',
        'Greece': 'GR',
        'Turquie': 'TR',
        'Turkey': 'TR',
        'Canada': 'CA',
        'Australie': 'AU',
        'Australia': 'AU',
        'Inde': 'IN',
        'India': 'IN',
        'Chine': 'CN',
        'China': 'CN',
        'Corée du Sud': 'KR',
        'South Korea': 'KR',
        'Thaïlande': 'TH',
        'Thailand': 'TH',
        'Maroc': 'MA',
        'Morocco': 'MA',
        'ROUMANIE': 'RO',
        'Romania': 'RO',
        'HONGRIE': 'HU',
        'Hungary': 'HU',
        'SERBIE': 'RS',
        'Serbia': 'RS',
        'IBIZA': 'ES',
        'BOOM': 'BE',
        'AMSTERDAM': 'NL',
        'CLUJ-NAPOCA': 'RO',
        'SPLIT': 'HR',
        'LAS VEGAS': 'US',
        'MIAMI': 'US',
        'EDC': 'US',
        'ULTRA': 'US',
        'België': 'BE',
        'Baslanden': 'NL',
        'United States': 'US',
        'Liége': 'BE',
        'Liege': 'BE',
        'Nimes': 'FR',
        'Nîmes': 'FR',
        'Belfort': 'FR',
        'Alpe d\'Huez': 'FR',
        'Alpe d’Huez': 'FR',
        'Fribourg': 'DE',
        'Boom': 'BE',
        'Split': 'HR',
        'Zrce': 'HR',
        'Zrće': 'HR',
        'Ibiza': 'ES',
        'Madrid': 'ES',
        'Barcelone': 'ES',
        'Barcelona': 'ES',
        'Weeze': 'DE',
        'Hilvarenbeek': 'NL',
        'Amsterdam': 'NL',
        'Bruxelles': 'BE',
        'Brussels': 'BE',
        'Prague': 'CZ',
        'Praha': 'CZ',
        'London': 'GB',
        'Londres': 'GB',
        'Berlin': 'DE',
        'Paris': 'FR',
        'Lyon': 'FR',
        'Marseille': 'FR',
        'Nice': 'FR',
        'Toulouse': 'FR',
        'Montréal': 'CA',
        'Montreal': 'CA',
        'Toronto': 'CA',
        'Vancouver': 'CA',
        'Sydney': 'AU',
        'Melbourne': 'AU',
        'Tokyo': 'JP',
        'Seoul': 'KR',
        'Séoul': 'KR',
        'Bangkok': 'TH',
        'Singapore': 'SG',
        'Singapour': 'SG',
        'Hong Kong': 'HK',
        'Shanghai': 'CN',
        'Beijing': 'CN',
        'Pékin': 'CN',
        'Abu Dhabi': 'AE',
        'Riyadh': 'SA',
        'Riyad': 'SA',
        'Doha': 'QA',
        'Istanbul': 'TR',
        'Tel Aviv': 'IL',
        'Moscow': 'RU',
        'Moscou': 'RU',
        'Kiev': 'UA',
        'Kyiv': 'UA',
    };

    const normalize = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
    const normalizedCountry = normalize(country);
    const normalizedFirstPart = normalize(parts[0]);

    const foundCode = Object.entries(countryCodes).find(
        ([key]) => normalize(key) === normalizedCountry || normalize(key) === normalizedFirstPart
    );

    return foundCode ? foundCode[1] : '';
};

export const getCountryFlag = (location: string): string => {
    const code = getCountryCode(location);
    if (!code) return '';

    // Traditional emoji flag converter
    const codePoints = code
        .toUpperCase()
        .split('')
        .map(char => 127397 + char.charCodeAt(0));
    return String.fromCodePoint(...codePoints);
};
